---
- name: make prod image tomcat
  hosts: docker
  become: yes

  tasks:
    - name: build new image
      docker_image:
        name: 'anresarm/tomcat_hello'
        source: build
        build:
          path: /tmp/img
          dockerfile: |
            FROM tomcat:9.0
            COPY /tmp/hello-1.0.war /usr/local/tomcat/webapps
            CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
...