---
- name: run build container
  hosts: docker
  become: yes

  tasks:
    - name: add needed software
      apt:
        name:
          - docker.io
          - python
          - python-pip
        update_cache: yes
        state: present

    - name: add model 'pip install docker-py'
      command: pip install docker-py
      state: present

    - name: run detach container
      docker_container:
        name: 'build_stand'
        image: 'kaabert/maven-with-git:corretto-8'
        state: started
        command: tail -f /dev/null
        detach: yes

    - name: get project from GIT and bild WAR
      shell: |
        docker exec build_stand git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /tmp/prj
        docker exec -w /tmp/prj build_stand /usr/share/maven/bin/mvn package -DskipTests

    - name: get WAR from container
      shell:
        docker cp build_stand:/tmp/prj/target/hello-1.0.war /tmp/

    - name: kill unneeded container
      docker_container:
        name: 'build_stand'
        state: absent
...

# 1. при запуске ошибка
# - "msg": "Failed to import docker-py - No module
# named requests.exceptions. Try `pip install docker-py`"
# (!) надо доустановить модуль docker-py
# Чтобы проверить установку модуля в Python, используйте
# pip show <имя_модуля>
# (!) Обязательно установить apt install python-pip