---
- name: run build container
  hosts: docker
  become: yes

  tasks:
    - name: add needed software
      apt:
        name:
          docker.io
        update_cache: yes
        state: present

    - name: run detach container
      docker_container:
        name: 'build_stand'
        image: 'kaabert/maven-with-git:corretto-8'
        state: started
...