---
- name: make prod image tomcat
  hosts: docker
  become: yes

  tasks:
    - name: come in to docker registry
      docker_login:
        username: 'andresarm'
        password: 'VuesAdmin123#'
        email: 'wipefree@gmail.com'

    - name: push image to registry (anresarm/tomcat_hello:latest)
      docker_image:
        repository: 'anresarm/tomcat_hello'
        tag: 'latest'
        push: yes
...