---
- name: start prod from andresarm/tomcat_hello:latest
  hosts: prod
  become: yes

  tasks:
    - name: add needed software
      apt:
        name:
          - docker.io
          - python
          - python-pip
        update_cache: yes
        state: present

    - name: run detach container
      docker_container:
        name: 'prod_stand'
        image: 'andresarm/tomcat_hello:latest'
        ports: '8080:8080'
        state: started
        detach: yes
...